basePath: /v1/api
info:
  contact:
    email: hafifcyber@gmail.com
    name: Hafif Nur Muhammad
    url: https://hafifamudi.github.io/
  description: This News Topic Management service API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: News Topic Management API
  version: "1.0"
paths: {}
swagger: "2.0"
