all: True
dir: "mocks"
outpkg: "mocks"
packages:
  news-topic-management-service/internal/core/news/repository:
  news-topic-management-service/internal/core/news/service:
  news-topic-management-service/internal/core/topic/service:
  news-topic-management-service/internal/core/topic/repository:
