version: '3.8'

services:
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CLIENT: postgresql
      DB_USERNAME: postgres
      DB_PASSWORD: rootuser
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: news_topic_management_service
      APP_ENV: DEVELOPMENT_DOCKER
      APP_NAME: NEWS_TOPIC_MANAGEMENT_SERVICE
      JAEGER_URL: jaeger-collector:4318
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootuser
      POSTGRES_DB: news_topic_management_service
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - app-network
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - ./loki-data:/loki  # Mount a writable directory for Loki's data

  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    networks:
      - app-network
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs:/var/log # Ensure this path matches where your app writes logs

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - app-network
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus-config.yml

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"
      - "4318:4318"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  loki-data:
