global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'news-topic-app'
    static_configs:
      - targets: ['app:3333']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: 'promtail'
    static_configs:
      - targets: [ 'promtail:9080' ]

